name: APK_URETICI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: APK Derle
        uses: kivy/buildozer-action@master
        with:
          workdir: .
          buildozer_version: stable
      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Hazir-APK
          path: bin/*.apk
